question:
  q1:
    type: "content"
    question: "tset1"
  q2:
    type: "option"
    question: "test3"
    o1: "asd"
    o2: "a1"
    o3: "a2"
  q3:
    type: "selection"
    question: "asd22"
    s1: "t1"
    s2: "t2"
    s3: "t3"
  q4:
    type: "content"
    question: "test5"
